app:

    developer:
        name: '@developer.name@'
        url: '@developer.url@'
        email: '@developer.email@'

    title: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
